apiVersion: v1
kind: Secret
metadata:
  name: quay-io-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJabXgxZUdWdWN6QXJZbTl2ZEdOaGJYQmliM1E2VmtKYU1qVkRPVTg1VURsWVUwZFlUekpQT0RSVFRGQktXbEpDU3pWT1JVVXhPRXBYUlZnMk5WTk9UVnBJVFRKTFZrczVPRGxPVURSQ05GUkZOa3BKVWc9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
